### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by hvelarde** [collective/Products.Ploneboard#42]
can we have a new release of this package? we need those bug fixes and Brazilian Portuguese translations in production.

**Comment by cillianderoiste** [comment]
It would also be great to have a release because of the bug which is fixed by 5b8d13c92, thanks!

**Comment by sureshvv** [comment]
Version 3.6 released

**Comment by merpdotcom** [comment]
Would love to have Ploneboard or equivalent of Ploneboard's basic functions in Plone 5x.

**Comment by tkimnguyen** [comment]
I’m curious if Ploneboard works with Plone 5. Have you tried it? (I realize you may not have been able to, if you’re not in a position to test it with git checkouts). A couple of years ago I wrote a post on our forum https://community.plone.org showing step by step how you can get default Plone to be a basic bulletin board.

**Comment by merpdotcom** [comment]
I am happy to try by any means possible. The basic plone as BB (if it is the one you are referencing that I think you are) doesn't meet the various community site's needs, Ploneboard does very well doing so. The communities do _not_ need heavier weight or dedicate forum software like Discourse or others, and break the preferred integration and security preferences we love from Plone. 
I would need some semi-step-by-step guidance on how to tweak Plone 5x to allow it to try to force Ploneboard install, since using straight buildout method (not surprisingly) fails to install. I have just installed the latest unified installed on my laptop for testing. If there is a way to tweak/pin/whatever to make it work, I will gladly be a guinea pig to figure it out. :-)

buildout.cfg  eggs:  Products.Ploneboard

https://www.pastiebin.com/5bcf99629f7c3

**Comment by tkimnguyen** [comment]
Ok. What was the error message and stack trace you got?

**Comment by merpdotcom** [comment]
The pastiebin link in the previous post isn't sufficient error info? If  that is not sufficient then I will re-run with more verbosity.

**Comment by hvelarde** [comment]
guys, your conversation here is completely off topic; please use proper channels.
